/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as DashboardOwnerRepoRouteImport } from './routes/dashboard/$owner/$repo'
import { Route as ApiGithubSecretsRouteImport } from './routes/api/github/secrets'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiGithubReposSearchRouteImport } from './routes/api/github/repos.search'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRepoRoute = DashboardOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiGithubSecretsRoute = ApiGithubSecretsRouteImport.update({
  id: '/api/github/secrets',
  path: '/api/github/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposSearchRoute = ApiGithubReposSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiGithubReposRoute,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/hello': typeof ApiHelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/repos': typeof ApiGithubReposRouteWithChildren
  '/api/github/secrets': typeof ApiGithubSecretsRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/github/repos/search': typeof ApiGithubReposSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/hello': typeof ApiHelloRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/repos': typeof ApiGithubReposRouteWithChildren
  '/api/github/secrets': typeof ApiGithubSecretsRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/github/repos/search': typeof ApiGithubReposSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/hello': typeof ApiHelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/github/repos': typeof ApiGithubReposRouteWithChildren
  '/api/github/secrets': typeof ApiGithubSecretsRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/github/repos/search': typeof ApiGithubReposSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/hello'
    | '/dashboard/'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/repos'
    | '/api/github/secrets'
    | '/dashboard/$owner/$repo'
    | '/api/auth/github/callback'
    | '/api/github/repos/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/hello'
    | '/dashboard'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/repos'
    | '/api/github/secrets'
    | '/dashboard/$owner/$repo'
    | '/api/auth/github/callback'
    | '/api/github/repos/search'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/hello'
    | '/dashboard/'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/github/repos'
    | '/api/github/secrets'
    | '/dashboard/$owner/$repo'
    | '/api/auth/github/callback'
    | '/api/github/repos/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHelloRoute: typeof ApiHelloRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiGithubReposRoute: typeof ApiGithubReposRouteWithChildren
  ApiGithubSecretsRoute: typeof ApiGithubSecretsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$owner/$repo': {
      id: '/dashboard/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/dashboard/$owner/$repo'
      preLoaderRoute: typeof DashboardOwnerRepoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/github/secrets': {
      id: '/api/github/secrets'
      path: '/api/github/secrets'
      fullPath: '/api/github/secrets'
      preLoaderRoute: typeof ApiGithubSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos/search': {
      id: '/api/github/repos/search'
      path: '/search'
      fullPath: '/api/github/repos/search'
      preLoaderRoute: typeof ApiGithubReposSearchRouteImport
      parentRoute: typeof ApiGithubReposRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOwnerRepoRoute: typeof DashboardOwnerRepoRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOwnerRepoRoute: DashboardOwnerRepoRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

interface ApiGithubReposRouteChildren {
  ApiGithubReposSearchRoute: typeof ApiGithubReposSearchRoute
}

const ApiGithubReposRouteChildren: ApiGithubReposRouteChildren = {
  ApiGithubReposSearchRoute: ApiGithubReposSearchRoute,
}

const ApiGithubReposRouteWithChildren = ApiGithubReposRoute._addFileChildren(
  ApiGithubReposRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiGithubReposRoute: ApiGithubReposRouteWithChildren,
  ApiGithubSecretsRoute: ApiGithubSecretsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
